### ISSUE TITLE
Holding down SPACE and D lets you park sideways perfectly

### ISSUE THREAD

**Issue by szabolcsdombi** [trekhleb/self-parking-car-evolution#11]
There is some issue with the brake that is constantly shaking the car and allowing the user to move the car sideways.

![Animation](https://user-images.githubusercontent.com/11232402/135126935-8e75f7ea-4611-424a-82e8-565c94181bbe.gif)

This project is great.

**Comment by trekhleb** [comment]
That's a fun finding :D 
Thanks for reporting that!

**Comment by DevBrent** [comment]
Working on getting the genes or a new network to solve for this (or better) on it's own.

**Comment by uid4oe** [comment]
looks like a feature to me 😄
